version: '3.8'
services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    env_file:
      - .env
    networks:
      - postgres-network
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
#      - ./db-data/:/var/lib/postgresql/data/
      - ./src/main/resources/init.sql:/docker-entrypoint-initdb.d/init.sql

networks:
  postgres-network:
    driver: bridge